export const PRODUCT_SPECIFICATIONS = {
  IPHONE: {
    SPECIFICATION: [
      "Display",
      "Processor",
      "Battery",
      "Operating System",
      "Water Resistance",
    ],
    CAMERA: ["Front Camera", "Rear Camera"],
    DIMENSION: ["Height", "Width", "Depth", "Weight"],
  },
  SMARTPHONE: {
    SPECIFICATION: [
      "display",
      "battery",
      "operatingSystem",
      "waterResistance",
      "sensors",
      "connectivity",
      "healthTracking",
    ],
    CAMERA: [],
    DIMENSION: ["height", "width", "depth", "weight"],
  },
  LAPTOP: {
    SPECIFICATION: [
      "ScreenSize",
      "Resolution",
      "RefreshRate",
      "SmartTV",
      "OperatingSystem",
      "Ports",
      "AudioOutput",
      "Connectivity",
    ],
    CAMERA: [],
    DIMENSION: ["Height", "Width", "Đepth", "Weight"],
  },
  SAMSUNG: {
    SPECIFICATION: [
      "type",
      "battery",
      "connectivity",
      "noiseCancellation",
      "frequencyResponse",
      "impedance",
      "waterResistance",
    ],
    CAMERA: [],
    DIMENSION: ["weight"],
  },
  BOOK: {
    SPECIFICATION: [
      "author",
      "publisher",
      "publicationYear",
      "genre",
      "language",
      "pageCount",
      "format",
      "isbn",
    ],
    DIMENSION: ["height", "width", "depth", "weight"],
  },
};
