export const constant_product_detail = {
  id: "66eb862471534a1f9cb11354",
  name: "Samsung Galaxy S24 Ultra Chính hãng VN/A",
  imageURL: null,
  primaryImageURL: null,
  description:
    '<h2><strong><span style="color: #fa5252">Đặc điểm nổi bật của Samsung Galaxy S24 Ultra 12GB 256GB</span></strong></h2><ul><li><p>Trải nghiệm đỉnh cao với hiệu năng mạnh mẽ từ vi xử lý tân tiến, kết hợp cùng RAM 12GB cho khả năng đa nhiệm mượt mà.</p></li><li><p>Lưu trữ thoải mái mọi ứng dụng, hình ảnh và video với bộ nhớ trong 256GB.</p></li><li><p>Nâng tầm nhiếp ảnh di động với hệ thống camera tiên tiến, cho ra đời những bức ảnh và video chất lượng chuyên nghiệp.</p></li><li><p>Thiết kế sang trọng, đẳng cấp, khẳng định phong cách thời thượng.</p></li></ul><p><strong><span style="color: #fa5252">Samsung S24 Ultra</span></strong> là siêu phẩm <strong>smartphone </strong>đỉnh cao mở đầu năm <strong>2024 </strong>đến từ nhà Samsung với chip <strong>Snapdragon 8 Gen 3 For Galaxy </strong>mạnh mẽ, công nghệ tương lai <strong>Galaxy AI</strong> cùng <strong>khung viền Titan</strong> đẳng cấp hứa hẹn sẽ mang tới nhiều sự thay đổi lớn về mặt thiết kế và cấu hình. SS&nbsp;Galaxy S24 bản Ultra&nbsp;sở hữu màn hình <strong>6.8 inch Dynamic</strong> <strong>AMOLED 2X tần số quét 120Hz</strong>. Máy cũng sở hữu camera chính <strong>200MP</strong>, camera zoom quang học <strong>50MP</strong>, camera tele <strong>10MP </strong>và camera góc siêu rộng <strong>12MP</strong>.<br></p><h2><strong><span style="color: #fa5252">Vì sao nên mua Samsung Galaxy S24 Ultra?</span></strong></h2><p style="text-align: justify">Đầu năm 2024, Samsung cho ra mắt <strong>Samsung S24 Ultra</strong> – Flagship dẫn đầu xu hướng với <strong>công nghệ AI</strong> tích hợp cùng nhiều tính năng và ưu điểm vượt trội khác. Các tính năng AI nổi bật trên điện thoại Samsung mới nhất bao gồm:</p><ul><li><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">Galaxy AI với các tính năng </span><strong><span style="color: rgb(0, 0, 0)">Khoanh tròn để tìm kiếm</span></strong><span style="color: rgb(0, 0, 0)">, </span><strong><span style="color: rgb(0, 0, 0)">Photo Assist, Live Translate, Note Assist</span></strong><span style="color: rgb(0, 0, 0)">.</span></p></li><li><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">Khung viền bằng </span><strong><span style="color: rgb(0, 0, 0)">titan cứng cáp</span></strong><span style="color: rgb(0, 0, 0)">, giúp thiết bị bền bỉ theo thời gian.</span></p></li><li><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">Các phiên bản màu lấy cảm hứng từ chất liệu đá tự nhiên, mang đến vẻ đẹp sang trọng và hiện đại.</span></p></li><li><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">Camera tích hợp công nghệ AI tuyệt đỉnh</span></strong><span style="color: rgb(0, 0, 0)">, nâng tầm chất lượng và khả năng xử lý hình ảnh.</span></p></li><li><p style="text-align: justify"><span style="color: rgb(0, 0, 0)">Hiệu năng cực đỉnh với chip </span><strong><span style="color: rgb(0, 0, 0)">Snapdragon 8 Gen3</span></strong><span style="color: rgb(0, 0, 0)"> for Galaxy, chiến game mượt mà.</span></p></li></ul><ul><li><p style="text-align: justify"><strong><span style="color: rgb(0, 0, 0)">Pin khoẻ 5000mAh</span></strong><span style="color: rgb(0, 0, 0)">, kéo dài thời gian sử dụng cả ngày dài, để không bỏ lỡ khoảnh khắc quan trọng.</span></p></li></ul>',
  brandName: "Apple",
  sellingTypes: "In-store selling only",
  categories: [
    {
      name: "Smart phone",
      level: 1,
    },
    {
      name: "Electronic",
      level: 0,
    },
  ],
  dimensions: {
    id: "66eb862471534a1f9cb11353",
    weight: 235.0,
    length: 3.0,
    width: 3.0,
    height: 4.0,
  },
  hasVariants: true,
  variants: [
    {
      id: "66eb862471534a1f9cb1136d",
      productId: "66eb862471534a1f9cb11354",
      primary: true,
      variantTypes: "COLOR",
      value: "midnight",
      imageURLs: [
        "https://cdn2.cellphones.com.vn/x/media/catalog/product/s/a/samsung-galaxy-z-fold-6-xanh_5_.png",
        "https://cdn2.cellphones.com.vn/x/media/catalog/product/s/a/samsung-galaxy-z-fold-6-xanh_6_.png",
        "https://cdn2.cellphones.com.vn/x/media/catalog/product/s/a/samsung-galaxy-z-fold-6-xanh_2_.png",
        "https://cdn2.cellphones.com.vn/x/media/catalog/product/s/a/samsung-galaxy-z-fold-6-xanh_4_.png",
        "https://cdn2.cellphones.com.vn/x/media/catalog/product/s/a/samsung-galaxy-z-fold-6-xanh_7_.png",
        "https://cdn2.cellphones.com.vn/x/media/catalog/product/s/a/samsung-galaxy-z-fold-6-xanh_3_.png",
        "https://cdn2.cellphones.com.vn/x/media/catalog/product/s/a/samsung-galaxy-z-fold-6-xanh_1_.png",
        "https://plus.unsplash.com/premium_photo-1674777843441-04dd6cd672ee?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fG1hbiUyMGZhc2hpb258ZW58MHx8MHx8fDA%3D",
      ],
      variantOptions: [
        {
          id: "66eb862471534a1f9cb11355",
          variantTypes: "RAM",
          value: "4GB",
          optionValues: [
            {
              id: "66eb862471534a1f9cb1135b",
              variantTypes: "STORAGE",
              value: "64GB",
              quantity: 120,
              price: 120.0,
              salePrice: 100.0,
              sku: "SS1-B-4GB-64GB",
              mrsp: 120.0,
            },
            {
              id: "66eb862471534a1f9cb1135c",
              variantTypes: "STORAGE",
              value: "128GB",
              quantity: 45,
              price: 6745.0,
              salePrice: 100.0,
              sku: "SS1-B-4GB-128GB",
              mrsp: 45.0,
            },
            {
              id: "66eb862471534a1f9cb1135d",
              variantTypes: "STORAGE",
              value: "256GB",
              quantity: 3465,
              price: 4567.0,
              salePrice: 100.0,
              sku: "SS1-B-4GB-256GB",
              mrsp: 4567.0,
            },
          ],
        },
        {
          id: "66eb862471534a1f9cb11356",
          variantTypes: "RAM",
          value: "8GB",
          optionValues: [
            {
              id: "66eb862471534a1f9cb1135e",
              variantTypes: "STORAGE",
              value: "64GB",
              quantity: 567,
              price: 867.0,
              salePrice: 100.0,
              sku: "SS1-B-8GB-64GB",
              mrsp: 867.0,
            },
            {
              id: "66eb862471534a1f9cb1135f",
              variantTypes: "STORAGE",
              value: "128GB",
              quantity: 234,
              price: 345.0,
              salePrice: 100.0,
              sku: "SS1-B-8GB-128GB",
              mrsp: 345.0,
            },
            {
              id: "66eb862471534a1f9cb11360",
              variantTypes: "STORAGE",
              value: "256GB",
              quantity: 87,
              price: 567.0,
              salePrice: 100.0,
              sku: "SS1-B-8GB-256GB",
              mrsp: 567.0,
            },
          ],
        },
        {
          id: "66eb862471534a1f9cb11357",
          variantTypes: "RAM",
          value: "16GB",
          optionValues: [
            {
              id: "66eb862471534a1f9cb11361",
              variantTypes: "STORAGE",
              value: "64GB",
              quantity: 645,
              price: 234.0,
              salePrice: 100.0,
              sku: "SS1-B-16GB-64GB",
              mrsp: 234.0,
            },
            {
              id: "66eb862471534a1f9cb11362",
              variantTypes: "STORAGE",
              value: "128GB",
              quantity: 12015,
              price: 7876.0,
              salePrice: 100.0,
              sku: "SS1-B-16GB-128GB",
              mrsp: 7876.0,
            },
            {
              id: "66eb862471534a1f9cb11363",
              variantTypes: "STORAGE",
              value: "256GB",
              quantity: 73,
              price: 5678.0,
              salePrice: 73.0,
              sku: "SS1-B-16GB-256GB",
              mrsp: 5678.0,
            },
          ],
        },
      ],
    },
    {
      id: "66eb862471534a1f9cb1136e",
      productId: "66eb862471534a1f9cb11354",
      primary: true,
      variantTypes: "COLOR",
      value: "titan",
      imageURLs: [
        "https://cdn2.cellphones.com.vn/x/media/catalog/product/s/a/samsung-galaxy-z-fold-6-hong_2_.png",
        "https://cdn2.cellphones.com.vn/x/media/catalog/product/s/a/samsung-galaxy-z-fold-6-hong_6_.png",
        "https://cdn2.cellphones.com.vn/x/media/catalog/product/s/a/samsung-galaxy-z-fold-6-hong_5_.png",
        "https://cdn2.cellphones.com.vn/x/media/catalog/product/s/a/samsung-galaxy-z-fold-6-hong_4_.png",
        "https://cdn2.cellphones.com.vn/x/media/catalog/product/s/a/samsung-galaxy-z-fold-6-hong_7_.png",
        "https://cdn2.cellphones.com.vn/x/media/catalog/product/s/a/samsung-galaxy-z-fold-6-hong_3_.png",
        "https://cdn2.cellphones.com.vn/x/media/catalog/product/s/a/samsung-galaxy-z-fold-6-hong_1_.png",
      ],
      variantOptions: [
        {
          id: "66eb862471534a1f9cb11358",
          variantTypes: "RAM",
          value: "4GB",
          optionValues: [
            {
              id: "66eb862471534a1f9cb11364",
              variantTypes: "STORAGE",
              value: "64GB",
              quantity: 120,
              price: 120.0,
              salePrice: 100.0,
              sku: "SS1-B-4GB-64GB",
              mrsp: 120.0,
            },
            {
              id: "66eb862471534a1f9cb11365",
              variantTypes: "STORAGE",
              value: "128GB",
              quantity: 45,
              price: 6745.0,
              salePrice: 100.0,
              sku: "SS1-B-4GB-128GB",
              mrsp: 45.0,
            },
            {
              id: "66eb862471534a1f9cb11366",
              variantTypes: "STORAGE",
              value: "256GB",
              quantity: 3465,
              price: 4567.0,
              salePrice: 100.0,
              sku: "SS1-B-4GB-256GB",
              mrsp: 4567.0,
            },
          ],
        },
        {
          id: "66eb862471534a1f9cb11359",
          variantTypes: "RAM",
          value: "8GB",
          optionValues: [
            {
              id: "66eb862471534a1f9cb11367",
              variantTypes: "STORAGE",
              value: "64GB",
              quantity: 567,
              price: 867.0,
              salePrice: 100.0,
              sku: "SS1-B-8GB-64GB",
              mrsp: 867.0,
            },
            {
              id: "66eb862471534a1f9cb11368",
              variantTypes: "STORAGE",
              value: "128GB",
              quantity: 234,
              price: 345.0,
              salePrice: 100.0,
              sku: "SS1-B-8GB-128GB",
              mrsp: 345.0,
            },
            {
              id: "66eb862471534a1f9cb11369",
              variantTypes: "STORAGE",
              value: "256GB",
              quantity: 87,
              price: 567.0,
              salePrice: 100.0,
              sku: "SS1-B-8GB-256GB",
              mrsp: 567.0,
            },
          ],
        },
        {
          id: "66eb862471534a1f9cb1135a",
          variantTypes: "RAM",
          value: "16GB",
          optionValues: [
            {
              id: "66eb862471534a1f9cb1136a",
              variantTypes: "STORAGE",
              value: "64GB",
              quantity: 645,
              price: 234.0,
              salePrice: 100.0,
              sku: "SS1-B-16GB-64GB",
              mrsp: 234.0,
            },
            {
              id: "66eb862471534a1f9cb1136b",
              variantTypes: "STORAGE",
              value: "128GB",
              quantity: 12015,
              price: 7876.0,
              salePrice: 100.0,
              sku: "SS1-B-16GB-128GB",
              mrsp: 7876.0,
            },
            {
              id: "66eb862471534a1f9cb1136c",
              variantTypes: "STORAGE",
              value: "256GB",
              quantity: 73,
              price: 5678.0,
              salePrice: 73.0,
              sku: "SS1-B-16GB-256GB",
              mrsp: 5678.0,
            },
          ],
        },
      ],
    },
  ],
};
