export const constant_specifications = {
  IPHONE: {
    SPECIFICATION: [
      "Display",
      "Processor",
      "Battery",
      "Operating System",
      "Water Resistance",
    ],
    CAMERA: ["Front Camera", "Rear Camera"],
    DIMENSION: ["Height", "Width", "Depth", "Weight"],
  },
  BANNERS: {
    SPECIFICATION: [
      "display",
      "processor",
      "ram",
      "storage",
      "battery",
      "operatingSystem",
      "graphicsCard",
      "ports",
    ],
    CAMERA: ["Front"],
    DIMENSION: ["Height", "Width", "Depth", "Weight"],
  },
  ELECTRONIC: {
    SPECIFICATION: [
      "display",
      "battery",
      "operatingSystem",
      "waterResistance",
      "sensors",
      "connectivity",
      "healthTracking",
    ],
    CAMERA: [],
    DIMENSION: ["height", "width", "depth", "weight"],
  },
  PHONE: {
    SPECIFICATION: [
      "display",
      "processor",
      "ram",
      "storage",
      "battery",
      "operatingSystem",
      "connectivity",
      "stylusSupport",
    ],
    CAMERA: ["front", "rear"],
    DIMENSION: ["height", "width", "depth", "weight"],
  },
  LAPTOP: {
    SPECIFICATION: [
      "ScreenSize",
      "Resolution",
      "RefreshRate",
      "SmartTV",
      "OperatingSystem",
      "Ports",
      "AudioOutput",
      "Connectivity",
    ],
    CAMERA: [],
    DIMENSION: ["Height", "Width", "Đepth", "Weight"],
  },
  SPORTS: {
    SPECIFICATION: [
      "type",
      "battery",
      "connectivity",
      "noiseCancellation",
      "frequencyResponse",
      "impedance",
      "waterResistance",
    ],
    CAMERA: [],
    DIMENSION: ["weight"],
  },
  WATCHES: {
    SPECIFICATION: [
      "type",
      "battery",
      "connectivity",
      "noiseCancellation",
      "frequencyResponse",
      "impedance",
      "waterResistance",
    ],
    CAMERA: [],
    DIMENSION: ["weight"],
  },
  GAMES: {
    SPECIFICATION: [
      "type",
      "battery",
      "connectivity",
      "noiseCancellation",
      "frequencyResponse",
      "impedance",
      "waterResistance",
    ],
    CAMERA: [],
    DIMENSION: ["weight"],
  },
  FURNITURE: {
    SPECIFICATION: [
      "type",
      "battery",
      "connectivity",
      "noiseCancellation",
      "frequencyResponse",
      "impedance",
      "waterResistance",
    ],
    CAMERA: [],
    DIMENSION: ["weight"],
  },
  SAMSUNG: {
    SPECIFICATION: [
      "type",
      "battery",
      "connectivity",
      "noiseCancellation",
      "frequencyResponse",
      "impedance",
      "waterResistance",
    ],
    CAMERA: [],
    DIMENSION: ["weight"],
  },
  BOOKS: {
    // Sách
    SPECIFICATION: [
      "author",
      "publisher",
      "publicationYear",
      "genre",
      "language",
      "pageCount",
      "format",
      "isbn",
    ],
    DIMENSION: ["height", "width", "depth", "weight"],
  },
  JEWELRY: {
    // Trang sức
    SPECIFICATION: [
      "material",
      "stoneType",
      "weight",
      "carat",
      "style",
      "gender",
    ],
    DIMENSION: ["length", "width", "height", "weight"],
  },
};
