export const SPECIFICATIONS_GROUPS = [
  {
    group_name: "SPECIFICATIONS",
    options: [
      "Display",
      "Processor",
      "Battery",
      "Operating System",
      "Water Resistance",
      "Sensors",
      "Health Tracking",
      "Screen Size",
      "Resolution",
      "Refresh Rate",
      "Smart TV",
      "Ports",
      "Audio Output",
      "Type",
      "Connectivity",
      "Noise Cancellation",
      "Frequency Response",
      "Impedance",
      "Author",
      "Publisher",
      "Publication Year",
      "Genre",
      "Language",
      "Page Count",
      "Format",
      "ISBN",
    ],
  },
  {
    group_name: "CAMERA",
    options: ["Front Camera", "Rear Camera"],
  },
  {
    group_name: "DIMENSION",
    options: ["Height", "Width", "Depth", "Weight"],
  },
];
