export const productModel = {
  name: "",
  description: "",
  specifications: [],
  category: null,
  subCategory: null,
  variants: [],
  primaryVariantType: "",
  width: null,
  weight: null,
  length: null,
  breadth: null,
  unitWeight: "",
  packageUnit: "",
  brandName: "",
  sku: "",
  quantityAvailable: 0,
  sellingType: "ONLINE",
  originalPrice: null,
  discountedPrice: null,
  sellingPrice: null,
  hasVariants: false,
  collections: [],
  variantOptionsTable: [],
  // variantImages: [],
  // primaryImage: "",
  // productImages: [],
};
