export const productModel = {
  name: "",
  description: "",
  category: "",
  specifications: [],
  subCategory: "",
  variants: [],
  primaryVariantType: "",
  // variantImages: [],
  // variantOptionsTable: [],
  // brandName: "",
  // sellingType: "ONLINE",
  // sku: "",
  // quantityAvailable: null,
  // originalPrice: null,
  // discountedPrice: null,
  // sellingPrice: null,
  // hasSpecification: false,
  // hasCollection: false,
  // hasVariants: false,
  // isFeatured: false,
  // width: null,
  // weight: null,
  // length: null,
  // breadth: null,
  // unitWeight: "",
  // packageUnit: "",
  // primaryImage: "",
  // productImages: [],
  // collections: [],
};
